### ISSUE TITLE
Any way to receive notifications even after app close ?

### ISSUE THREAD

**Issue by dotnetdreamer** [Alone2/capacitor-notificationlistener#3]
It would be awesome to have this feature.

**Comment by Alone2** [comment]
Yes, it is possible to receive notifications when the app is closed, although it's not implemented directly into the plugin.

You need another plugin such as [background-task](https://capacitorjs.com/docs/apis/background-task) or [capacitor-persistent-notification](https://github.com/flytesoft-software/capacitor-persistent-notification) to achieve this outcome.  Capacitor-persistent-notification is probably the better choice, because  the "background-task" documentation states: ```This method should finish in less than 3 minutes or your app risks being terminated by the OS```, although I think there are ways to circumvent this issue.  I didn't implement "background notification listening" directly into the plugin, as there are multiple ways of doing it and I wanted to leave the choice to the developers.

[Here](https://github.com/Alone2/test-angular/blob/master/src/main.ts) is an example using capacitor-persistent-notification. I didn't test it that well, so it's possible that the example still has bugs.

I hope I was able to help you :smile:
